"""add image analysis fields

Revision ID: d531fe699281
Revises: add_user_role
Create Date: 2026-08-25 20:29:23.398177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd531fe699281'
down_revision: Union[str, Sequence[str], None] = 'add_user_role'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('image_category', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('image_issue', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('image_severity', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('image_severity_score', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('image_confidence', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('final_priority_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'final_priority_score')
    op.drop_column('complaints', 'image_confidence')
    op.drop_column('complaints', 'image_severity_score')
    op.drop_column('complaints', 'image_severity')
    op.drop_column('complaints', 'image_issue')
    op.drop_column('complaints', 'image_category')
    # ### end Alembic commands ###
